### ISSUE TITLE
Tearing/Strobing: Linux

### ISSUE THREAD

**Issue by CyborgPotato** [cloudhead/rx#114]
Compiling and launching `rx` from the latest commit on Linux results in the following tearing/strobing:

https://user-images.githubusercontent.com/10701143/116639050-9a2e0480-a935-11eb-8b09-800f2b506f75.mov

System Information:
``` 
Kernel: 5.11.16-1-default
Distro: openSUSE Tumbleweed
nvidia-version: 460.73.01
Graphics Card: RTX 2070
```

**Comment by cloudhead** [comment]
Never seen this before in rx, but looks like screen tearing. I think it makes sense to offer an option to enable double buffering and/or vsync. I can look into it.
