### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by talas** [cloudhead/rx#117]
Hi, great program!

However, the current binary release is version 0.4.0 which does not contain the fix for non-US layouts (https://github.com/cloudhead/rx/pull/88). Thus I can't enter command mode.

Also, trying to compile on Debian 10 (and probably other non-rolling distros) fail, since the packaged rustc of 1.41 is too old.
Errors out about matches_macro being unstable, this was fixed in rustc 1.42 it seems.

Would it be possible to get a new release up?

Thanks!

**Comment by cloudhead** [comment]
Yeah, I've been planning to do this soon!

**Comment by cloudhead** [comment]
v0.5.0 was released.
