### ISSUE TITLE
Can it output to apng or only gif?

### ISSUE THREAD

**Issue by vi** [cloudhead/rx#13]

**Comment by cloudhead** [comment]
In current master, only .gif (animated) and .png (non-animated) are supported outputs, and only .png is supported as input.

**Comment by cloudhead** [comment]
Wasn't aware of this format actually - I'll probably add support for it later down the line, maybe via the apng-encoder crate.

**Comment by cloudhead** [comment]
Rx now spits out an error if you try to save in an unsupported format.

**Comment by ssokolow** [comment]
Just a word of warning, anything which relies on the libpng reference implementation of PNG will never support APNG because it is an explicit violation of the PNG specification.

> The first eight bytes of a PNG datastream always contain the following (decimal) values:
> 
>     137 80 78 71 13 10 26 10
> This signature indicates that the remainder of the datastream contains a single PNG image, consisting of a series of chunks beginning with an [IHDR](https://www.w3.org/TR/PNG/#11IHDR) chunk and ending with an [IEND](https://www.w3.org/TR/PNG/#11IEND) chunk.
> 
> -- https://www.w3.org/TR/PNG/#5DataRep

> PNG also does not support multiple images in one file. This restriction is a reflection of the reality that many applications do not need and will not support multiple images per file. In any case, single images are a fundamentally different sort of object from sequences of images. Rather than make false promises of interchangeability, we have drawn a clear distinction between single-image and multi-image formats. PNG is a single-image format.
> 
> -- https://www.w3.org/TR/PNG-Rationale.html

Mozilla, who created APNG because they disagreed with the conclusion of PNG's creators that animated GIF was a mistake, maintain their own fork of libpng with APNG support because of this.

**Comment by cloudhead** [comment]
Hmm interesting. I've moved towards writing one file per frame with the `w/frames` command (undocumented), as an alternative. It's easy to take that and produce whatever you want from it.
