### ISSUE TITLE
No way to scroll the help screen

### ISSUE THREAD

**Issue by Serif-7** [cloudhead/rx#130]
Correct me if I'm wrong, but I don't see a way to scroll when I enter the `:help` screen. The only way to see more of the docs is to expand the window, and even fully expanded it's still cut off on my fairly large monitor.

**Comment by cloudhead** [comment]
You can use the pan tool with `<spacebar>`!

**Comment by guysv** [comment]
just commenting that handling arrows could also be intuitive. I had to google this issue to figure that one out lol.
