### ISSUE TITLE
[Request] Background color

### ISSUE THREAD

**Issue by kramer425** [cloudhead/rx#17]
I might have missed it in the help menu, but it would be great to be able to change the background color of the window to something other than black - trying to draw black/dark sprites

**Comment by cloudhead** [comment]
One thing you can do is `set checker`. You can turn it off with `unset checker`

**Comment by rbisewski** [comment]
I'm exploring ideas about how to do this in a [branch](https://github.com/rbisewski/rx/tree/17-set-background-color-rc2).

Cloudhead, do you know if there is an easy way to access the UI programmatically? Or where it gets initialized?

**Comment by cloudhead** [comment]
Looking at how the checker is implemented should give you some ideas: https://github.com/cloudhead/rx/blob/master/src/renderer.rs#L447-L450

The `Session` is accessible read-only from the renderer, so you can access any setting from there.

**Comment by rbisewski** [comment]
Thanks for that :)

I have since made a pull request.

**Comment by rbisewski** [comment]
Should this issue be closed now that the PR has been merged?

**Comment by cloudhead** [comment]
Fixed in 6e2f20340e0c82d97e24f15fdd5b97d49ac262bb
