### ISSUE TITLE
Non-Qwerty keyboards broken with current defaults

### ISSUE THREAD

**Issue by g2p** [cloudhead/rx#18]
I figured out that I need to enable the `winit` feature to get proper key mappings on my non-qwerty keyboard.
Maybe this should be documented, or enabled by default.

**Comment by cloudhead** [comment]
Do the default key bindings usually work for you in other software? Can you give an example of what's not working and what layout are you using? Thanks.

**Comment by g2p** [comment]
I'm using azerty.
Almost all software works by default, everything follows the keyboard layout, which is great except for the occasional game that uses a hard-coded, non-remappable WASD.
[Here's a map](https://www.reddit.com/r/MapPorn/comments/1cgmcn/keyboard_layouts_in_europe_530x739/) for perspective.

**Comment by g2p** [comment]
The first thing I tried was to enter command mode, I got zoom-in instead, and had to grep the source to find what was going on.

**Comment by g2p** [comment]
Could you start by blessing winit over glfw?
Having two divergent ways of handling key bindings is bound to break expectations.
I haven't had any trouble once I enabled the winit feature, and if it starts behaving strangely grepping for accesses to the scancode field would make it very easy to pinpoint the issue.
Also, by keeping interactions close to vim, I don't think you will be required to do anything that doesn't localize.

**Comment by cloudhead** [comment]
> Could you start by blessing winit over glfw

Unfortunately not - winit has significant problems on macOS. I’m not sure actually why the two handle keys differently - potentially there might be a way to have winit’s behavior in glfw. I’m looking into that now.

**Comment by cloudhead** [comment]
I pushed a change to master that should fix this with `glfw`. Do you want to give it a try? You won't be able to map all keys on the azerty layout, but it should work for all keys accessible without 'shift' on the qwerty layout.

**Comment by g2p** [comment]
I tried it, it works fine.
Thank you!
