### ISSUE TITLE
name conflicts with rx

### ISSUE THREAD

**Issue by akhepcat** [cloudhead/rx#24]
rx is already a well-known name ("receive-xmodem")  as as such conflicts with the package when installed.

Consider changing the name to something that isn't currently conflicting, such as 'vx'  or 'px'

**Comment by cloudhead** [comment]
Thanks for the suggestion, but I won't be changing the name at this point, as it's too much of a hassle and I like it as it is. If it's a problem, you can simply rename the binary to `rx-editor` for example.
