### ISSUE TITLE
[Suggestion] Create a makefile to simplify installation process

### ISSUE THREAD

**Issue by agraven** [cloudhead/rx#3]
Adding a makefile would significantly simplify the installation process, and also make it easier to automate for packaging purposes. I'll gladly submit a PR with one if requested.

Super neat software, by the way :)

**Comment by zicklag** [comment]
Maybe use [Cargo Make](https://github.com/sagiegurari/cargo-make). It's kind of neat, cross-platform, and written in Rust.

**Comment by cloudhead** [comment]
Everything required is now embedded in the binary, so shouldn’t require any additional installation. Closing but feel free to re-open if it’s not working for you.
