### ISSUE TITLE
Request: Support cmd+q on macOS

### ISSUE THREAD

**Issue by Phrohdoh** [cloudhead/rx#4]

**Comment by cloudhead** [comment]
This now works via the glfw backend. Please re-open if you’re still encountering the issue 👍

**Comment by Phrohdoh** [comment]
Does `winit` not provide support for this at all?

**Comment by cloudhead** [comment]
Not out of the box - it would require extra code in rx as far as I know. `glfw` is now the default on master, because it also just works better overall on macOS.
