### ISSUE TITLE
rx: unknown tool "sampler"

### ISSUE THREAD

**Issue by seletskiy** [cloudhead/rx#41]
Version: `v0.2.0` 8b2d7ba

### Steps to reproduce

1. Remove config (`~/.config/rx/init.rx`);
2. Start `rx`.

### Result

`rx` doesn't start with following error message:

```
rx: unknown tool "sampler"
```

### Workaround

It seems that problem is that `rx` generates invalid `init.rx` which contains following line:

```
map/n  <ctrl>        :tool sampler {:tool -}                   --  Sample color (hold)
```

Removing this line from `init.rx` fixes problem.

**Comment by cloudhead** [comment]
Thanks, fixed here: https://github.com/cloudhead/rx/commit/a41cf9a14b1e62275ea2638547378b06bdfa35f7
