### ISSUE TITLE
keyboard nav 

### ISSUE THREAD

**Issue by abbey-titcomb** [cloudhead/rx#43]
seems like I can't hold down the keyboard keys to scroll across frames. this makes it super tough to nav between frames when fixing mistakes. also a short cut to choose frames as a focus would be nice as when I zoom, it moves to the center axis for some reason?

**Comment by cloudhead** [comment]
Both issues should be fixed now!

I've changed it so that zooming with the mouse/touchpad always zooms towards the cursor. Zooming with the keyboard zooms to the center of the active view.

Also key repeats are back.
