### ISSUE TITLE
macOS 0.3 zipped Release won't open on Catalina

### ISSUE THREAD

**Issue by simlay** [cloudhead/rx#46]
Hi! This is a pretty cool project and I was gonna test it out and ran into this:

I downloaded https://github.com/cloudhead/rx/releases/download/v0.3.0/rx-0.3.0-x86_64.app.zip as found on https://rx.cloudhead.io/.

I tried right click->open as well as just regularly double clicking but got the following error.

![image](https://user-images.githubusercontent.com/1163510/71560844-a04f6080-2a23-11ea-89bb-74cd156572b3.png)

**Comment by cloudhead** [comment]
Hmm that's unfortunate - does it give no other information? Looking around, some people recommend doing a `chmod +x` on the binary, inside the `.app` bundle. :thinking:

**Comment by simlay** [comment]
Oh, that fixed it! `cd rx.app/Contents/MacOS && chmod +x ./rx` fixed it.

**Comment by cloudhead** [comment]
Ok, after investigating more - it seems like depending on how you unzip the the .app, it may or may not end up executable! This is probably why it's a bad idea to distribute as a .zip.

If I unzip by double-clicking, all good. If I unzip with `unzip` on the CLI, it's not executable.

**Comment by simlay** [comment]
Hmm. Initially, I unzipped via the chrome "open" functionality (click on the downloaded file in chrome) which ideally runs the same way that double click works in finder. After more testing though, it's not an executable when I unzip via `unzip` in bash or double clicking. I think that most applications are distributed as `.dmg`, probably for reasons similar to this.

**Comment by cloudhead** [comment]
I see.. I've created a `.tar.gz`, since that preserves the executable bit, and link that one instead from the website. Hopefully that works for everyone!

**Comment by simlay** [comment]
Yup! Works for me!
