### ISSUE TITLE
debug does not play nice with checker

### ISSUE THREAD

**Issue by pop** [cloudhead/rx#55]
I noticed some strange behavior today when `checker` and `deubg` are both enabled.

Steps to reproduce:
:one:  Set `checker = true` and `debug = true` in your `init.rx` (or similar) config file. You can also set these in a running session.
:two:  Open `rx`.
:three: Using the arrow keys navigate up and down.
:white_square_button:  Notice that the edit window and checker patterns go in opposite directions.

I can take a look at this when I get a chance. If you have any pointers on where the problem/fix might be I would appreciate the direction.

**Comment by cloudhead** [comment]
Nice catch, was a simple fix: 36a320a

**Comment by pop** [comment]
:+1:
