### ISSUE TITLE
error setting grid, expected '='

### ISSUE THREAD

**Issue by jennypollack** [cloudhead/rx#65]
following https://rx.cloudhead.io/guide.html
trying to set the grid
`:set grid/spacing 4 4`
get `Error: expected '='`

**Comment by cloudhead** [comment]
Good catch! In this case the guide is wrong, it should be `:set grid/spacing = 4 4`.

**Comment by cloudhead** [comment]
Fixed here https://github.com/cloudhead/rx.cloudhead.io/commit/7190722ac53a0c5f3fb83718b510c74b948b918b

**Comment by jennypollack** [comment]
hmm, i'm not seeing a grid, have set the color as well, any ideas?

**Comment by jennypollack** [comment]
ah ok, had to also run `:set grid`

**Comment by cloudhead** [comment]
Yeah I will eventually have a `:grid` command that does both at once.
