### ISSUE TITLE
Allow panning in help mode

### ISSUE THREAD

**Issue by jennypollack** [cloudhead/rx#69]
<img width="1677" alt="Screen Shot 2020-04-03 at 1 01 13 PM" src="https://user-images.githubusercontent.com/3885055/78353927-3955c080-75ab-11ea-975c-33a67ae6463e.png">

**Comment by cloudhead** [comment]
Ah yes.. scale applies everywhere so you need a large enough screen. The best solution I guess would be to allow panning/scrolling somehow :thinking:

**Comment by cloudhead** [comment]
Fixed in https://github.com/cloudhead/rx/commit/8274340209d021bb576165ff3843db87fea37edd
