### ISSUE TITLE
"gl" feature seems to be missing.

### ISSUE THREAD

**Issue by vi** [cloudhead/rx#7]
> thread 'main' panicked at 'No adapters found. Please enable the feature for one of the graphics backends: vulkan, metal, dx12, dx11, gl', src/libcore/option.rs:1166:5

> "gl"

> `cargo install --force --git https://github.com/cloudhead/rx --locked --features gl`

> `Package `rx v0.1.0 (https://github.com/cloudhead/rx#465f95f4)` does not have these features: `gl``

**Comment by vi** [comment]
And Vulkan does not work: `thread 'main' panicked at 'Unable to create Vulkan instance: VkError(ERROR_INCOMPATIBLE_DRIVER)', src/libcore/result.rs:1084:5`.

Does `rx` work on legacy-ish Linux desktop systems?

**Comment by vi** [comment]
It's custom-built `4.19.18`, Linux Debian Buster amd64, Intel HD Graphics 4000, i915.

But in any case discrepancy between error message and actually supported features should be fixed one way or another.

**Comment by vi** [comment]
After installing `mesa-vulkan-drivers` error message changed:

```
[2019-08-26T19:04:20Z ERROR rx::session] Error sourcing `palettes/sweetie16.palette`: "palettes/sweetie16.palette" not found
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
thread 'main' panicked at 'assertion failed: surface.raw.supports_queue_family(&adapter.queue_families[0])', /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.3.3/src/device.rs:1836:9
```

**Comment by vi** [comment]
After adding `Option      "DRI"    "3"` to `xorg.conf` it finally started and showed window:

```
$ ~/.cargo/bin/rx 
[2019-08-26T19:17:40Z ERROR rx::session] Error sourcing `palettes/sweetie16.palette`: "palettes/sweetie16.palette" not found
INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete
```

But if OpenGL is supported, it still should be exposed in Cargo features. And if not, it should be removed from panic message.

**Comment by cloudhead** [comment]
Interesting, thanks. The panic message is coming from an underlying library - I'll check if I can add gl support easily.

**Comment by JavaScriptDude** [comment]
For those who are trying on Ubuntu using Vulkan and seeing the 'No Adapters Found' error from `rx`, Make sure that vulkan is installed correctly by using `vulkaninfo` command. If that utility gives an error then you will need to resolve this.

My resolution on Ubuntu 18.04 was to use Synaptic package manager to reinstall all my nvidia packages. After which , `vulkaninfo` gave good output and `rx` started working.

**Comment by cloudhead** [comment]
There's a GL backend now which should work on all hardware: https://github.com/cloudhead/rx/pull/50 - give it a try.

**Comment by pickfire** [comment]
It works but very lag and slow. The mouse seemed very slow to move when entering the window.

**Comment by cloudhead** [comment]
@pickfire can you `:set debug` in rx and tell me what the numbers displayed are? The gl backend should be just as fast as the vulkan one.

**Comment by pickfire** [comment]
`8.27ms 0.03ms 0MB 422KB normal`. Maybe it was lag because I was connected to a monitor bigger than my laptop (my laptop is only 1366x768 with intel integrated graphics 4000 ~9 years old).
