### ISSUE TITLE
Error sourcing `palettes/sweetie16.palette`: "palettes/sweetie16.palette" not found

### ISSUE THREAD

**Issue by vi** [cloudhead/rx#8]
Something seems missing after `cargo install`.

Probably some basic palette should be embedded into executable with `include_bytes!()` or whatever to make it self-sufficient.

Alternatively (maybe better), entire `config` from git may be zipped and embedded into rx executable and unpacked on first start if `$XDG_CONFIG_HOME/rx` is missing.

**Comment by cloudhead** [comment]
That's an interesting idea :thinking: 

For now, you can download the palette from https://cloudhead.io/rx/palettes/ into `~/.config/rx/palettes`

**Comment by karuppiah7890** [comment]
@cloudhead I also get this error even after putting the default sweetie16 palette in the `~/.config/rx/palettes` directory. But when my current working directory is `~/.config/rx/` it works fine.

**Comment by cloudhead** [comment]
@karuppiah7890 can you tell me what OS are you on, and if you're on `master` or `v0.1.0`?

**Comment by karuppiah7890** [comment]
I tried it with `master` and `0.1.0` too. Looks like only current working directory config is being taken somehow. I don't know rust so not able to understand how to go about the issue and debug it

**Comment by karuppiah7890** [comment]
Also, I have never worked with a pixel editor before, this was my first time. This looks so cool ! :D and I wanted to mention that master works well. `0.1.0` didn't save a GIF for me, even though I saved it as `.gif`, it instead stored PNG I think, but master saved a GIF and I was able to see the animation 😁

**Comment by cloudhead** [comment]
The palette is now inlined in the `init.rx` which is embedded in the binary, so this should be solved.

@karuppiah7890 if you have related issues, please open a new issue : )
