### ISSUE TITLE
Parser fails on multiple arguments command including Rgba8

### ISSUE THREAD

**Issue by MonsieurLanza** [cloudhead/rx#94]
For instance `paint/color #ff017d 32 49` fails with
```
Error: expected ’/’, got ` 32 49`
```

I get same problem with https://github.com/cloudhead/rx/pull/93

**Comment by cloudhead** [comment]
Indeed, the color parser is broken. I just pushed a fix to master that should solve it: 661f7a2

**Comment by MonsieurLanza** [comment]
Thanks.
